services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PORT=80
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
