services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      PORT: 80
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://user:password@database:5432/movieh"
      ENV: test
    networks:
      - app-network
    ports:
      - "8001:8000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17-alpine
    networks:
      - app-network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movieh
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:

volumes:
  db-data: