# Generated by Django 5.1.2 on 2024-12-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_remove_userprofile_comedy_userprofile_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genres', models.JSONField(default=list)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('duration', models.IntegerField()),
                ('shortDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizedMovie',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restapi.movie')),
            ],
            bases=('restapi.movie',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_movies',
            field=models.ManyToManyField(related_name='users', to='restapi.movie'),
        ),
    ]
