# Generated by Django 5.1.2 on 2024-12-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_movie_recommendation_personalizedmovie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedmovie',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
