# Generated by Django 5.1.2 on 2024-12-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_rename_score_personalizedmovie_personalization_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizedmovie',
            name='movie_ptr',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='PersonalizedMovie',
        ),
    ]
