name: Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
  push:
    paths:
      - "backend/**"
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          cd ${{ github.workspace }}/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run lint
        run: |
          cd ${{ github.workspace }}/backend
          flake8 .
      - name: Run Tests
        run: |
          cd ${{ github.workspace }}/backend
          python manage.py test
